// Fruits Corner - Product Catalog & Categories Data

export const categories = [
  { id: 'all', name: 'All Fruits', count: 8 },
  { id: 'apples', name: 'Apples', image: '/images/cat-apples.jpg', count: 3 },
  { id: 'bananas', name: 'Bananas', image: '/images/cat-bananas.jpg', count: 2 },
  { id: 'oranges', name: 'Oranges', image: '/images/cat-oranges.jpg', count: 2 },
  { id: 'grapes', name: 'Grapes', image: '/images/cat-grapes.jpg', count: 3 },
  { id: 'mangoes', name: 'Mangoes', image: '/images/cat-mangoes.jpg', count: 4 },
  { id: 'berries', name: 'Berries', image: '/images/cat-berries.jpg', count: 3 },
  { id: 'seasonal', name: 'Seasonal', image: '/images/cat-seasonal.jpg', count: 5 }
];

export const products = [
  {
    id: 'prod-1',
    name: 'Fresh Apples',
    category: 'apples',
    tag: 'Best Seller',
    price: 120,
    unit: 'kg',
    originalPrice: 150,
    rating: 4.8,
    reviewsCount: 120,
    image: '/images/prod-apples.jpg',
    description: 'Crisp, sweet, and handpicked Himalayan Royal Gala apples. Packed with dietary fiber, antioxidants, and natural sweetness.',
    nutrition: { calories: '52 kcal', carbs: '14g', vitaminC: '14%', fiber: '2.4g' },
    farm: 'Kinnaur Orchards, Himachal',
    isBestSeller: true
  },
  {
    id: 'prod-2',
    name: 'Premium Bananas',
    category: 'bananas',
    tag: 'Daily Fresh',
    price: 60,
    unit: 'kg',
    originalPrice: 75,
    rating: 4.9,
    reviewsCount: 95,
    image: '/images/prod-bananas.jpg',
    description: 'Golden ripe Yelakki and Robusta bananas. High in potassium, instant energy, and naturally tree-ripened without harmful carbides.',
    nutrition: { calories: '89 kcal', carbs: '23g', potassium: '358mg', fiber: '2.6g' },
    farm: 'Jalgaon Farms, Maharashtra',
    isBestSeller: true
  },
  {
    id: 'prod-3',
    name: 'Juicy Oranges',
    category: 'oranges',
    tag: 'Citrus Boost',
    price: 80,
    unit: 'kg',
    originalPrice: 100,
    rating: 4.7,
    reviewsCount: 88,
    image: '/images/prod-oranges.jpg',
    description: 'Sun-kissed Nagpur sweet oranges bursting with fresh tangy juice. Rich in Vitamin C to supercharge your immunity.',
    nutrition: { calories: '47 kcal', carbs: '12g', vitaminC: '88%', calcium: '40mg' },
    farm: 'Nagpur Organic Groves, Maharashtra',
    isBestSeller: true
  },
  {
    id: 'prod-4',
    name: 'Alphonso Mangoes',
    category: 'mangoes',
    tag: 'King of Fruits',
    price: 250,
    unit: 'kg',
    originalPrice: 320,
    rating: 5.0,
    reviewsCount: 210,
    image: '/images/prod-mangoes.jpg',
    description: 'Original Ratnagiri Alphonso (Hapus) mangoes known for their intoxicating aroma, saffron-gold pulp, and unmatched sweetness.',
    nutrition: { calories: '60 kcal', carbs: '15g', vitaminA: '21%', fiber: '1.6g' },
    farm: 'Ratnagiri Estate, Konkan Coast',
    isBestSeller: true
  },
  {
    id: 'prod-5',
    name: 'Kashmiri Strawberries',
    category: 'berries',
    tag: 'Fresh Arrival',
    price: 180,
    unit: 'pack',
    originalPrice: 220,
    rating: 4.9,
    reviewsCount: 64,
    image: '/images/prod-berries.jpg',
    description: 'Plump, ruby-red strawberries harvested at peak ripeness. Perfect for smoothies, breakfast bowls, or healthy snacking.',
    nutrition: { calories: '33 kcal', carbs: '8g', vitaminC: '98%', fiber: '2g' },
    farm: 'Kashmir Valley Greenhouses',
    isBestSeller: false
  },
  {
    id: 'prod-6',
    name: 'Seedless Grapes',
    category: 'grapes',
    tag: 'Sweet Crunch',
    price: 140,
    unit: 'kg',
    originalPrice: 170,
    rating: 4.8,
    reviewsCount: 76,
    image: '/images/prod-grapes.jpg',
    description: 'Crisp green and purple seedless grapes, naturally sweet and chilled. High in resveratrol and heart-healthy polyphenols.',
    nutrition: { calories: '69 kcal', carbs: '18g', vitaminK: '18%', fiber: '0.9g' },
    farm: 'Nashik Vineyards, Maharashtra',
    isBestSeller: false
  },
  {
    id: 'prod-7',
    name: 'Sun-Gold Kiwis',
    category: 'seasonal',
    tag: 'Immunity Boost',
    price: 160,
    unit: 'pack',
    originalPrice: 190,
    rating: 4.8,
    reviewsCount: 52,
    image: '/images/prod-kiwi.jpg',
    description: 'Exotic golden kiwis with sweet tropical flavor and smooth skin. Contains 3x more Vitamin C than standard oranges.',
    nutrition: { calories: '61 kcal', carbs: '15g', vitaminC: '150%', fiber: '3g' },
    farm: 'Arunachal Hill Orchards',
    isBestSeller: false
  },
  {
    id: 'prod-8',
    name: 'Golden Pineapple',
    category: 'seasonal',
    tag: 'Farm Special',
    price: 90,
    unit: 'pc',
    originalPrice: 110,
    rating: 4.6,
    reviewsCount: 43,
    image: '/images/prod-pineapple.jpg',
    description: 'Extra sweet, juicy Queen pineapple. Loaded with natural bromelain enzymes to aid digestion and reduce inflammation.',
    nutrition: { calories: '50 kcal', carbs: '13g', bromelain: 'High', vitaminC: '79%' },
    farm: 'Vazhakulam Groves, Kerala',
    isBestSeller: false
  }
];
